export const DEFAULT_COURSE_THEME = "akadion"
export const COURSE_THEMES = [
  {
    key: "akadion",
    label: "Bleu Pastel",
    accent: "from-[#dce8f5] via-[#c5daf0] to-[#accbe8]",
    swatch: "bg-linear-to-br from-[#dce8f5] via-[#c5daf0] to-[#accbe8]",
    text: "text-[#2c4a6f]",
    tabActive: "bg-linear-to-r from-[#d9e7f5] via-[#c7dcf0] to-[#b3d3eb] text-[#1e3a5f] border border-[#9ec3e3] shadow-sm font-semibold",
    tabInactive: "bg-[#f2f7fc] text-[#3d5a7d] hover:bg-[#e4eff8] border border-[#d2e2f0]",
    badge: "bg-[#2c4a6f]/12 text-[#1e3a5f]",
    heroBg: "bg-[#f5f9fe]",
    heroBorder: "border-[#bdd5ef]",
    heroAccent: "#6b9fcf",
    heroStatBg: "bg-[#eaf2fb] border border-[#bdd5ef]",
    heroStatText: "text-[#1e3a5f]",
    heroStatLabel: "text-[#4a7aab]",
    // In-page accents
    weekNumBg: "bg-[#ddeaf9]",
    weekNumText: "text-[#1e3a5f]",
    iconBg: "bg-[#ddeaf9]",
    iconText: "text-[#2c4a6f]",
    btnIconBg: "bg-[#ddeaf9]",
    btnIconBorder: "border-[#bdd5ef]",
    btnIconText: "text-[#2c4a6f]",
    btnPrimaryBg: "bg-[#3b6ea8]",
    btnPrimaryHover: "hover:bg-[#2e5a8e]",
    linkColor: "text-[#3b6ea8]",
    sectionLabel: "text-[#4a7aab]",
    sectionTitle: "text-[#1e3a5f]",
    fileIconBg: "bg-[#ddeaf9]",
    fileIconText: "text-[#2c4a6f]",
    studentInitialBg: "bg-[#ddeaf9]",
    studentInitialText: "text-[#1e3a5f]",
  },
  {
    key: "ocean-blue",
    label: "Azuriu Pastel",
    accent: "from-[#d5f3f7] via-[#b6ebf2] to-[#92e0eb]",
    swatch: "bg-linear-to-br from-[#d5f3f7] via-[#b6ebf2] to-[#92e0eb]",
    text: "text-[#005f73]",
    tabActive: "bg-linear-to-r from-[#d2f1f5] via-[#b4eaef] to-[#91dfea] text-[#004d40] border border-[#7ed8e5] shadow-sm font-semibold",
    tabInactive: "bg-[#effbfc] text-[#00695c] hover:bg-[#d8f4f7] border border-[#b8ebf2]",
    badge: "bg-[#005f73]/12 text-[#004d40]",
    heroBg: "bg-[#f0fbfd]",
    heroBorder: "border-[#90dce8]",
    heroAccent: "#2ab0c8",
    heroStatBg: "bg-[#e2f7fb] border border-[#90dce8]",
    heroStatText: "text-[#004d5e]",
    heroStatLabel: "text-[#007a8e]",
    weekNumBg: "bg-[#c8eef5]",
    weekNumText: "text-[#004d5e]",
    iconBg: "bg-[#c8eef5]",
    iconText: "text-[#005f73]",
    btnIconBg: "bg-[#c8eef5]",
    btnIconBorder: "border-[#90dce8]",
    btnIconText: "text-[#005f73]",
    btnPrimaryBg: "bg-[#0e8fa8]",
    btnPrimaryHover: "hover:bg-[#0a7a91]",
    linkColor: "text-[#0e8fa8]",
    sectionLabel: "text-[#007a8e]",
    sectionTitle: "text-[#004d5e]",
    fileIconBg: "bg-[#c8eef5]",
    fileIconText: "text-[#005f73]",
    studentInitialBg: "bg-[#c8eef5]",
    studentInitialText: "text-[#004d5e]",
  },
  {
    key: "forester",
    label: "Mentă Pastel",
    accent: "from-[#dcf5e3] via-[#beebd2] to-[#9fdfb9]",
    swatch: "bg-linear-to-br from-[#dcf5e3] via-[#beebd2] to-[#9fdfb9]",
    text: "text-[#1f5c35]",
    tabActive: "bg-linear-to-r from-[#d8f3e0] via-[#bbeacb] to-[#9adde8] text-[#1b4d24] border border-[#8fd7aa] shadow-sm font-semibold",
    tabInactive: "bg-[#f0faf3] text-[#2d6637] hover:bg-[#dff5e5] border border-[#c4ebd0]",
    badge: "bg-[#1f5c35]/12 text-[#1b4d24]",
    heroBg: "bg-[#f2fbf5]",
    heroBorder: "border-[#97d4b2]",
    heroAccent: "#28a05e",
    heroStatBg: "bg-[#e2f5ea] border border-[#97d4b2]",
    heroStatText: "text-[#1b4d24]",
    heroStatLabel: "text-[#2a7a44]",
    weekNumBg: "bg-[#c8ecd8]",
    weekNumText: "text-[#1b4d24]",
    iconBg: "bg-[#c8ecd8]",
    iconText: "text-[#1f5c35]",
    btnIconBg: "bg-[#c8ecd8]",
    btnIconBorder: "border-[#97d4b2]",
    btnIconText: "text-[#1f5c35]",
    btnPrimaryBg: "bg-[#1f8a4c]",
    btnPrimaryHover: "hover:bg-[#18743f]",
    linkColor: "text-[#1f8a4c]",
    sectionLabel: "text-[#2a7a44]",
    sectionTitle: "text-[#1b4d24]",
    fileIconBg: "bg-[#c8ecd8]",
    fileIconText: "text-[#1f5c35]",
    studentInitialBg: "bg-[#c8ecd8]",
    studentInitialText: "text-[#1b4d24]",
  },
  {
    key: "caramel",
    label: "Piersică Pastel",
    accent: "from-[#ffedd5] via-[#fed7aa] to-[#fdba74]",
    swatch: "bg-linear-to-br from-[#ffedd5] via-[#fed7aa] to-[#fdba74]",
    text: "text-[#9a3412]",
    tabActive: "bg-linear-to-r from-[#ffedd5] via-[#fed7aa] to-[#fdba74] text-[#7c2d12] border border-[#fb923c] shadow-sm font-semibold",
    tabInactive: "bg-[#fff7ed] text-[#9a3412] hover:bg-[#ffedd5] border border-[#fed7aa]",
    badge: "bg-[#9a3412]/12 text-[#7c2d12]",
    heroBg: "bg-[#fffbf5]",
    heroBorder: "border-[#f8c88c]",
    heroAccent: "#e8873a",
    heroStatBg: "bg-[#fff0d8] border border-[#f8c88c]",
    heroStatText: "text-[#7c2d12]",
    heroStatLabel: "text-[#b54a1a]",
    weekNumBg: "bg-[#fde3c4]",
    weekNumText: "text-[#7c2d12]",
    iconBg: "bg-[#fde3c4]",
    iconText: "text-[#9a3412]",
    btnIconBg: "bg-[#fde3c4]",
    btnIconBorder: "border-[#f8c88c]",
    btnIconText: "text-[#9a3412]",
    btnPrimaryBg: "bg-[#c9642a]",
    btnPrimaryHover: "hover:bg-[#ae5522]",
    linkColor: "text-[#c9642a]",
    sectionLabel: "text-[#b54a1a]",
    sectionTitle: "text-[#7c2d12]",
    fileIconBg: "bg-[#fde3c4]",
    fileIconText: "text-[#9a3412]",
    studentInitialBg: "bg-[#fde3c4]",
    studentInitialText: "text-[#7c2d12]",
  },
  {
    key: "dracula",
    label: "Levănțică Pastel",
    accent: "from-[#f3e8ff] via-[#e9d5ff] to-[#d8b4fe]",
    swatch: "bg-linear-to-br from-[#f3e8ff] via-[#e9d5ff] to-[#d8b4fe]",
    text: "text-[#6b21a8]",
    tabActive: "bg-linear-to-r from-[#f3e8ff] via-[#e9d5ff] to-[#d8b4fe] text-[#581c87] border border-[#c084fc] shadow-sm font-semibold",
    tabInactive: "bg-[#faf5ff] text-[#6b21a8] hover:bg-[#f3e8ff] border border-[#e9d5ff]",
    badge: "bg-[#6b21a8]/12 text-[#581c87]",
    heroBg: "bg-[#fbf5ff]",
    heroBorder: "border-[#c8a0f4]",
    heroAccent: "#8b3fd4",
    heroStatBg: "bg-[#f2e8ff] border border-[#c8a0f4]",
    heroStatText: "text-[#581c87]",
    heroStatLabel: "text-[#7c2caa]",
    weekNumBg: "bg-[#ecd9ff]",
    weekNumText: "text-[#581c87]",
    iconBg: "bg-[#ecd9ff]",
    iconText: "text-[#6b21a8]",
    btnIconBg: "bg-[#ecd9ff]",
    btnIconBorder: "border-[#c8a0f4]",
    btnIconText: "text-[#6b21a8]",
    btnPrimaryBg: "bg-[#7c2fcf]",
    btnPrimaryHover: "hover:bg-[#6a26b2]",
    linkColor: "text-[#7c2fcf]",
    sectionLabel: "text-[#7c2caa]",
    sectionTitle: "text-[#581c87]",
    fileIconBg: "bg-[#ecd9ff]",
    fileIconText: "text-[#6b21a8]",
    studentInitialBg: "bg-[#ecd9ff]",
    studentInitialText: "text-[#581c87]",
  },
  {
    key: "cherry-red",
    label: "Trandafir Pastel",
    accent: "from-[#ffe4e6] via-[#fecdd3] to-[#fda4af]",
    swatch: "bg-linear-to-br from-[#ffe4e6] via-[#fecdd3] to-[#fda4af]",
    text: "text-[#9f1239]",
    tabActive: "bg-linear-to-r from-[#ffe4e6] via-[#fecdd3] to-[#fda4af] text-[#881337] border border-[#fb7185] shadow-sm font-semibold",
    tabInactive: "bg-[#fff1f2] text-[#9f1239] hover:bg-[#ffe4e6] border border-[#fecdd3]",
    badge: "bg-[#9f1239]/12 text-[#881337]",
    heroBg: "bg-[#fff4f5]",
    heroBorder: "border-[#f8a0b0]",
    heroAccent: "#d43870",
    heroStatBg: "bg-[#ffe5e9] border border-[#f8a0b0]",
    heroStatText: "text-[#881337]",
    heroStatLabel: "text-[#b51a40]",
    weekNumBg: "bg-[#ffd5dc]",
    weekNumText: "text-[#881337]",
    iconBg: "bg-[#ffd5dc]",
    iconText: "text-[#9f1239]",
    btnIconBg: "bg-[#ffd5dc]",
    btnIconBorder: "border-[#f8a0b0]",
    btnIconText: "text-[#9f1239]",
    btnPrimaryBg: "bg-[#c0254e]",
    btnPrimaryHover: "hover:bg-[#a51e42]",
    linkColor: "text-[#c0254e]",
    sectionLabel: "text-[#b51a40]",
    sectionTitle: "text-[#881337]",
    fileIconBg: "bg-[#ffd5dc]",
    fileIconText: "text-[#9f1239]",
    studentInitialBg: "bg-[#ffd5dc]",
    studentInitialText: "text-[#881337]",
  },
]

export const COURSE_THEME_KEYS = new Set(COURSE_THEMES.map((theme) => theme.key))

export function getCourseTheme(themeKey) {
  return COURSE_THEMES.find((theme) => theme.key === themeKey) ?? COURSE_THEMES[0]
}

export function getThemeUserKey(user) {
  return user?.mail || user?.email || user?.id || "anonim"
}
